### ISSUE TITLE
in Zusammenarbeit mit Philipp Gusenleitner

### ISSUE THREAD

**Issue by JusterLuk** [rstropek-teaching/morse-code-quiz-5ahif-JusterLuk#1]

**Comment by rstropek** [comment]
@JusterLuk Thank you for your homework. Here are some tips for how you can improve:

* Use `Assert.AreEqual(a, b)` instead of `Assert.IsTrue(a == b)`
* Never check in `bin` or `obj` directories
* Use `[ExpectedException(typeof(...)]` if you expect a test to throw an exception
* Your tests should refer (e.g. using a comment) to **specific** requirements in the specification. If they test some behavior that was not explicitly required, add a description why the test is relevant.
* You code requires that the entire source text has to be in memory. That does not fully fulfill the requirements.
* You did not use .NET Core/Standard but .NET 4.5. Try to use the latest versions of .NET in this course.

Greetings,
Rainer Stropek.
